name: Glance
options:
  bundleIdPrefix: com.glance
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: zh-Hans

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "-"

targets:
  Glance:
    type: application
    platform: macOS
    sources:
      - path: GlanceApp.swift
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Services
      - path: Utils
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.glance.app
        INFOPLIST_FILE: ""
        INFOPLIST_KEY_CFBundleDisplayName: Glance
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
